# -*- coding: utf-8 -*-
"""lab 1 - topicos - resuelto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1deNYLb-2T0kr400fholEFmx88yAeMMEM

#EJERCICIO RESUELTO
"""

!pip install chromadb sentence-transformers

import chromadb
from chromadb.utils import embedding_functions

# Crear cliente en memoria (los datos se pierden al terminar la sesión)
client = chromadb.EphemeralClient()

print('Cliente ChromaDB creado exitosamente')
print(f'Versión de ChromaDB: {chromadb.__version__}')
print(f'Número de colecciones: {len(client.list_collections())}')

# 1. Instanciar la función de embedding por defecto
# Esta función genera vectores de 384 dimensiones
embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction()

# 2. Crear la colección 'articulos_academicos'
# get_or_create_collection: crea si no existe, o recupera si ya existe
collection = client.get_or_create_collection(
    name='articulos_academicos',
    embedding_function=embedding_fn,
    metadata={'hnsw:space': 'cosine'} # Métrica: similitud del coseno
)

print(f'Colección creada: {collection.name}')
print(f'Número de documentos inicial: {collection.count()}')

# Corpus de resúmenes de artículos académicos
documentos = [
    'Las redes neuronales convolucionales (CNN) han revolucionado el reconocimiento de imágenes...',
    'Los transformers y el mecanismo de atención son la base de los modelos de lenguaje como GPT y BERT...',
    'El aprendizaje por refuerzo permite a agentes autónomos aprender estrategias óptimas...',
    'Las bases de datos vectoriales como ChromaDB, Pinecone y Weaviate habilitan la búsqueda semántica...',
    'La generación aumentada por recuperación (RAG) combina LLMs con búsqueda vectorial...',
    'El fine-tuning de modelos preentrenados como BERT permite adaptar representaciones generales...',
    'Los embeddings multimodales permiten representar texto, imágenes y audio en un mismo espacio vectorial...',
    'PostgreSQL con la extensión pgvector integra capacidades de búsqueda vectorial en SQL...'
]

# Generar IDs automáticos: doc_001, doc_002, etc.
ids = [f'doc_{i+1:03d}' for i in range(len(documentos))]

# Metadatos para cada documento
metadatos = [
    {'categoria': 'vision_computacional', 'anio': 2024, 'relevancia': 'alta'},
    {'categoria': 'NLP', 'anio': 2024, 'relevancia': 'alta'},
    {'categoria': 'reinforcement_learning', 'anio': 2023, 'relevancia': 'media'},
    {'categoria': 'bases_de_datos', 'anio': 2025, 'relevancia': 'alta'},
    {'categoria': 'RAG', 'anio': 2025, 'relevancia': 'alta'},
    {'categoria': 'NLP', 'anio': 2024, 'relevancia': 'media'},
    {'categoria': 'multimodal', 'anio': 2024, 'relevancia': 'media'},
    {'categoria': 'bases_de_datos', 'anio': 2025, 'relevancia': 'alta'}
]

# INSERTAR EN LA COLECCIÓN
collection.add(
    documents=documentos,
    metadatas=metadatos,
    ids=ids
)

print(f'Documentos insertados: {collection.count()}')
print(f'IDs creados: {ids}')

# 1. Definir el texto de consulta en lenguaje natural
consulta = 'búsqueda semántica con inteligencia artificial'

# 2. Ejecutar la consulta: retornar los 3 documentos más similares
resultados = collection.query(
    query_texts=[consulta],
    n_results=3,            # Queremos el Top 3
    include=['documents', 'distances', 'metadatas'] # Qué datos queremos ver
)

# 3. Visualizar los resultados con un formato limpio
print(f"\nConsulta: '{consulta}'")
print('='*65)

for i, (doc, dist, meta) in enumerate(zip(
    resultados['documents'][0],
    resultados['distances'][0],
    resultados['metadatas'][0]
), start=1):

    # Convertir la distancia a un porcentaje de similitud (opcional para lectura humana)
    # En distancia del coseno, menor distancia = mayor similitud
    similitud = 1 - dist

    print(f"\nResultado #{i} | Similitud: {similitud:.4f}")
    print(f"Categoría: {meta['categoria']}")
    print(f"Año: {meta['anio']}")
    print(f"Texto: {doc[:100]}...") # Mostramos solo los primeros 100 caracteres

# 1. Definir consulta y filtros
consulta_2 = 'almacenamiento y gestión de vectores en bases de datos'

# 2. Ejecutar consulta híbrida
resultados_filtrados = collection.query(
    query_texts=[consulta_2],
    n_results=2,
    where={ # Filtro sobre metadatos
        "$and": [
            {"categoria": {"$eq": "bases_de_datos"}},
            {"anio": {"$gte": 2024}}
        ]
    },
    include=['documents', 'distances', 'metadatas']
)

# 3. Visualizar resultados
print(f"\nConsulta híbrida: '{consulta_2}'")
print(f"Filtro aplicado: categoria == 'bases_de_datos' AND anio >= 2024")
print('='*65)

for i, (doc_id, doc, dist, meta) in enumerate(zip(
    resultados_filtrados['ids'][0],
    resultados_filtrados['documents'][0],
    resultados_filtrados['distances'][0],
    resultados_filtrados['metadatas'][0]
), start=1):
    print(f"\nID: {doc_id} | Similitud: {(1-dist):.4f}")
    print(f"Texto: {doc[:90]}...")

# --- OPERACIONES CRUD ADICIONALES ---

# 1. ACTUALIZAR: Modificar metadatos de un documento existente (doc_003)
collection.update(
    ids=['doc_003'],
    metadatas=[{'categoria': 'reinforcement_learning', 'anio': 2024, 'relevancia': 'alta'}]
)
print('✅ Documento doc_003 actualizado exitosamente')

# 2. OBTENER: Recuperar un documento específico por su ID
resultado_get = collection.get(
    ids=['doc_003'],
    include=['documents', 'metadatas']
)
print(f'\nDocumento recuperado: doc_003')
print(f'Metadatos actualizados: {resultado_get["metadatas"][0]}')

# 3. ELIMINAR: Remover un documento por ID
collection.delete(ids=['doc_003'])
print(f'\n🗑️ Documento doc_003 eliminado')

# 4. CONTAR: Ver cuántos documentos quedan en total
print(f'Total de documentos restantes: {collection.count()}')

# 5. LISTAR: Ver las colecciones disponibles en el cliente
print(f'\nColecciones disponibles: {client.list_collections()}')

# --- MODO PERSISTENTE (Datos guardados en disco) ---

# 1. Crear cliente persistente (los datos se guardarán en la carpeta 'chromadb_lab01')
client_persistente = chromadb.PersistentClient(path='./chromadb_lab01')

# 2. Crear una nueva colección en este cliente
col_persistente = client_persistente.get_or_create_collection(
    name='mi_coleccion_persistente',
    embedding_function=embedding_functions.SentenceTransformerEmbeddingFunction()
)

# 3. Insertar un documento
col_persistente.add(
    documents=['Este documento sobrevivirá al reinicio de Python'],
    ids=['persist_001']
)

print(f'✅ Datos guardados en la carpeta: ./chromadb_lab01/')
print(f'Documentos en la nueva colección: {col_persistente.count()}')
print('Nota: Puedes ver la carpeta en el menú de archivos de la izquierda en Colab.')

"""#EJERCICIO 1"""

# Crear colección para el ejercicio 1
coleccion_cine = client.get_or_create_collection(
    name="peliculas_sci_fi",
    embedding_function=embedding_fn, # Reutilizamos la del paso 3
    metadata={"hnsw:space": "cosine"}
)

documentos_cine = [
    "Inception: Un ladrón que roba secretos a través del uso de la tecnología de compartir sueños.",
    "Interstellar: Un equipo de exploradores viaja a través de un agujero de gusano en el espacio.",
    "The Matrix: Un programador descubre que la realidad es una simulación creada por máquinas.",
    "Blade Runner 2049: Un joven blade runner descubre un secreto enterrado que podría sumir a la sociedad en el caos.",
    "Dune: El hijo de una familia noble trata de vengar la muerte de su padre mientras salva un planeta desértico.",
    "Arrival: Una lingüista es reclutada para comunicarse con alienígenas que han llegado a la Tierra.",
    "Gravity: Dos astronautas quedan varados en el espacio tras un accidente en su transbordador.",
    "The Martian: Un astronauta queda atrapado en Marte y debe sobrevivir con sus limitados recursos.",
    "Ex Machina: Un programador es invitado a evaluar las capacidades de una inteligencia artificial avanzada.",
    "Minority Report: En un futuro donde la policía arresta a criminales antes de que cometan el delito."
]

# IDs únicos
ids_cine = [f"movie_{i+1:03d}" for i in range(len(documentos_cine))]

# Al menos 2 metadatos (Género y Año por ejemplo)
metadatos_cine = [
    {"genero": "Suspenso", "anio": 2010},
    {"genero": "Aventura", "anio": 2014},
    {"genero": "Accion", "anio": 1999},
    {"genero": "Neo-noir", "anio": 2017},
    {"genero": "Epico", "anio": 2021},
    {"genero": "Drama", "anio": 2016},
    {"genero": "Drama", "anio": 2013},
    {"genero": "Supervivencia", "anio": 2015},
    {"genero": "IA", "anio": 2014},
    {"genero": "Accion", "anio": 2002}
]

coleccion_cine.add(documents=documentos_cine, ids=ids_cine, metadatas=metadatos_cine)

# --- EJERCICIO 1: CONSULTA #1 ---

# 1. Definimos una consulta conceptual
pregunta_1 = "películas que tratan sobre simulación de la realidad y computadoras"

# 2. Buscamos en la colección de cine que creaste antes
res_1 = coleccion_cine.query(
    query_texts=[pregunta_1],
    n_results=3,
    include=['documents', 'distances', 'metadatas']
)

# 3. Formateamos la salida como pide la guía
print(f"🔍 Consulta: '{pregunta_1}'")
print("-" * 60)

for i, (doc, dist, meta, doc_id) in enumerate(zip(
    res_1['documents'][0],
    res_1['distances'][0],
    res_1['metadatas'][0],
    res_1['ids'][0]
), start=1):

    similitud = 1 - dist
    print(f"Resultado #{i}:")
    print(f"  🆔 ID: {doc_id}")
    print(f"  📈 Similitud: {similitud:.4f}")
    print(f"  🎭 Género: {meta['genero']} | 📅 Año: {meta['anio']}")
    print(f"  📄 Texto: {doc}")
    print("-" * 30)

# --- EJERCICIO 1: CONSULTA #2 ---

# 1. Definimos una consulta conceptual
pregunta_2 = "películas que tratan sobre robots e inteligecia artificial con sentimientos"

# 2. Buscamos en la colección de cine que creaste antes
res_2 = coleccion_cine.query(
    query_texts=[pregunta_2],
    n_results=3,
    include=['documents', 'distances', 'metadatas']
)

# 3. Formateamos la salida como pide la guía
print(f"🔍 Consulta: '{pregunta_2}'")
print("-" * 60)

for i, (doc, dist, meta, doc_id) in enumerate(zip(
    res_2['documents'][0],
    res_2['distances'][0],
    res_2['metadatas'][0],
    res_2['ids'][0]
), start=1):

    similitud = 1 - dist
    print(f"Resultado #{i}:")
    print(f"  🆔 ID: {doc_id}")
    print(f"  📈 Similitud: {similitud:.4f}")
    print(f"  🎭 Género: {meta['genero']} | 📅 Año: {meta['anio']}")
    print(f"  📄 Texto: {doc}")
    print("-" * 30)

# --- EJERCICIO 1: CONSULTA #3 ---

# 1. Definimos una consulta conceptual
pregunta_3 = "películas que tratan sobre exploracion del espacio exterior y planetas lejanos"

# 2. Buscamos en la colección de cine que creaste antes
res_3 = coleccion_cine.query(
    query_texts=[pregunta_3],
    n_results=3,
    include=['documents', 'distances', 'metadatas']
)

# 3. Formateamos la salida como pide la guía
print(f"🔍 Consulta: '{pregunta_3}'")
print("-" * 60)

for i, (doc, dist, meta, doc_id) in enumerate(zip(
    res_3['documents'][0],
    res_3['distances'][0],
    res_3['metadatas'][0],
    res_3['ids'][0]
), start=1):

    similitud = 1 - dist
    print(f"Resultado #{i}:")
    print(f"  🆔 ID: {doc_id}")
    print(f"  📈 Similitud: {similitud:.4f}")
    print(f"  🎭 Género: {meta['genero']} | 📅 Año: {meta['anio']}")
    print(f"  📄 Texto: {doc}")
    print("-" * 30)

"""#EJERCICIO 2

##Definir los 4 Pares de Consultas
"""

import pandas as pd

# Definición de los pares de consultas (A y B)
pares_consultas = [
    ("viajes interestelares y agujeros de gusano", "exploración del espacio profundo y astrofísica"),
    ("inteligencia artificial y robots con conciencia", "máquinas pensantes y androides con sentimientos"),
    ("realidad virtual y simulación por computadora", "mundo digital falso creado por software"),
    ("supervivencia en marte y planetas hostiles", "quedar atrapado en el planeta rojo y vivir solo")
]

resultados_comparativa = []

# Función para calcular Jaccard: |A ∩ B| / |A ∪ B|
def calcular_jaccard(set_a, set_b):
    interseccion = len(set_a.intersection(set_b))
    union = len(set_a.union(set_b))
    return interseccion / union if union > 0 else 0

"""##Ejecutar las consultas y procesar datos"""

for q_a, q_b in pares_consultas:
    # Consulta A
    res_a = coleccion_cine.query(query_texts=[q_a], n_results=3)
    ids_a = set(res_a['ids'][0])
    sim_a = sum(res_a['distances'][0]) / 3 # Promedio distancia

    # Consulta B
    res_b = coleccion_cine.query(query_texts=[q_b], n_results=3)
    ids_b = set(res_b['ids'][0])
    sim_b = sum(res_b['distances'][0]) / 3 # Promedio distancia

    # Cálculos
    comunes = ids_a.intersection(ids_b)
    diferentes = ids_a.symmetric_difference(ids_b)
    jaccard = calcular_jaccard(ids_a, ids_b)

    resultados_comparativa.append({
        "Consulta A": q_a,
        "Consulta B": q_b,
        "IDs Comunes": list(comunes),
        "IDs Diferentes": list(diferentes),
        "Similitud Prom. A": round(1 - sim_a, 4),
        "Similitud Prom. B": round(1 - sim_b, 4),
        "Índice Jaccard": round(jaccard, 4)
    })

# Crear DataFrame para la tabla
df_comparativa = pd.DataFrame(resultados_comparativa)
display(df_comparativa)

"""#EJERCICIO 3

##Creación de la colección y carga de 15 documentos
"""

# 1. Crear la colección para el repositorio EPIS
repositorio_epis = client.get_or_create_collection(
    name="repositorio_epis",
    embedding_function=embedding_fn,
    metadata={"hnsw:space": "cosine"}
)

# 2. Datos simulados (15 documentos)
documentos_epis = [
    "Sistema de detección de intrusos basado en redes neuronales profundas para entornos IoT.",
    "Optimización de protocolos de enrutamiento en redes de sensores inalámbricos utilizando algoritmos genéticos.",
    "Análisis de vulnerabilidades en aplicaciones web modernas y propuestas de mitigación.",
    "Implementación de un modelo de procesamiento de lenguaje natural para el quechua.",
    "Arquitectura de microservicios escalables para sistemas de gestión académica universitaria.",
    "Uso de blockchain para asegurar la integridad de títulos académicos en la UNSA.",
    "Algoritmos de visión computacional para la clasificación automática de cultivos agrícolas.",
    "Evaluación del impacto de la realidad aumentada en el aprendizaje de ingeniería de software.",
    "Diseño de una red definida por software (SDN) para optimizar el tráfico en campus universitarios.",
    "Detección de malware en dispositivos Android mediante análisis dinámico y aprendizaje automático.",
    "Plataforma de telemedicina con cifrado de extremo a extremo para zonas rurales.",
    "Modelado de tráfico vehicular en Arequipa usando redes inteligentes.",
    "Seguridad en la nube: Un estudio sobre la prevención de ataques DDoS.",
    "Optimización de consultas en bases de datos NoSQL para Big Data.",
    "Desarrollo de un framework para pruebas automáticas en sistemas críticos."
]

metadatos_epis = [
    {"area": "IA", "anio": 2024, "autor": "L. Mamani", "turnitin": 12.5},
    {"area": "Redes", "anio": 2022, "autor": "J. Quispe", "turnitin": 8.0},
    {"area": "Seguridad", "anio": 2025, "autor": "M. Flores", "turnitin": 15.2},
    {"area": "IA", "anio": 2023, "autor": "R. Condori", "turnitin": 5.0},
    {"area": "Software", "anio": 2024, "autor": "A. Vargas", "turnitin": 18.9},
    {"area": "Seguridad", "anio": 2025, "autor": "E. Luna", "turnitin": 2.5},
    {"area": "IA", "anio": 2021, "autor": "G. Choque", "turnitin": 22.0},
    {"area": "Software", "anio": 2020, "autor": "K. Salas", "turnitin": 10.1},
    {"area": "Redes", "anio": 2025, "autor": "P. Diaz", "turnitin": 7.4},
    {"area": "Seguridad", "anio": 2023, "autor": "S. Huaman", "turnitin": 19.5},
    {"area": "Redes", "anio": 2024, "autor": "F. Paredes", "turnitin": 14.0},
    {"area": "IA", "anio": 2022, "autor": "V. Ramos", "turnitin": 9.8},
    {"area": "Seguridad", "anio": 2021, "autor": "C. Ortiz", "turnitin": 25.6},
    {"area": "Software", "anio": 2025, "autor": "L. Rojas", "turnitin": 4.2},
    {"area": "Software", "anio": 2023, "autor": "H. Torres", "turnitin": 11.3}
]

ids_epis = [f"tesis_{i+1:03d}" for i in range(len(documentos_epis))]

repositorio_epis.add(documents=documentos_epis, metadatas=metadatos_epis, ids=ids_epis)
print(f"✅ Repositorio EPIS listo con {repositorio_epis.count()} documentos.")

"""##Implementación de la función de búsqueda avanzada"""

def buscar_articulos(consulta, area=None, anio_desde=None, anio_hasta=None, max_turnitin=20, top_k=5):
    filtros = []

    # Agregar filtro de área
    if area:
        filtros.append({"area": {"$eq": area}})

    # Agregar filtro de Turnitin
    filtros.append({"turnitin": {"$lte": max_turnitin}})

    # Agregar filtros de rango de año
    if anio_desde:
        filtros.append({"anio": {"$gte": anio_desde}})
    if anio_hasta:
        filtros.append({"anio": {"$lte": anio_hasta}})

    # Combinar todos los filtros con $and
    filtro_final = {"$and": filtros} if len(filtros) > 1 else filtros[0]

    res = repositorio_epis.query(
        query_texts=[consulta],
        n_results=top_k,
        where=filtro_final
    )

    # Formateo de salida
    print(f"\n🔍 Buscando: '{consulta}' | Filtros: Area={area}, Turnitin Max={max_turnitin}%")
    for i in range(len(res['ids'][0])):
        print(f"[{i+1}] ID: {res['ids'][0][i]} | Similitud: {1 - res['distances'][0][i]:.4f}")
        print(f"    Autor: {res['metadatas'][0][i]['autor']} | Area: {res['metadatas'][0][i]['area']} | Año: {res['metadatas'][0][i]['anio']}")
        print(f"    Texto: {res['documents'][0][i][:80]}...")

# --- Prueba de las 4 combinaciones (Requerimiento M) ---
buscar_articulos("ataques cibernéticos", area="Seguridad", anio_desde=2024)
buscar_articulos("deep learning", area="IA", max_turnitin=10)
buscar_articulos("protocolos wifi", area="Redes", anio_desde=2020, anio_hasta=2023)
buscar_articulos("desarrollo web", max_turnitin=30, top_k=3)

"""##Función de Estadísticas"""

def estadisticas_repositorio(consulta_referencia):
    print(f"\n📊 ESTADÍSTICAS DEL REPOSITORIO (Ref: '{consulta_referencia}')")
    print("-" * 50)

    # 1. Contar por área
    areas = ["IA", "Redes", "Seguridad", "Software"]
    for a in areas:
        conteo = repositorio_epis.get(where={"area": a})
        print(f"Area {a}: {len(conteo['ids'])} documentos.")

        # 2. Similitud promedio por área
        if len(conteo['ids']) > 0:
            res_a = repositorio_epis.query(query_texts=[consulta_referencia], where={"area": a}, n_results=10)
            avg_sim = sum([1 - d for d in res_a['distances'][0]]) / len(res_a['distances'][0])
            print(f"   > Similitud promedio con la consulta: {avg_sim:.4f}")

estadisticas_repositorio("inteligencia artificial y ciberseguridad")

"""#EJERCICIO 4

##CONFIGURACION DE PERSISTENCIA
"""

# --- EJERCICIO 4: PASO 1 - PERSISTENCIA E INSERCIÓN DE DATOS ---

import chromadb
from chromadb.utils import embedding_functions
import os

# 1. Configurar el modelo de embedding
embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

# 2. Configurar el Cliente Persistente
# Los datos se guardarán en una carpeta llamada 'db_epis_unsa'
path_db = "./db_epis_unsa"
client_persiste = chromadb.PersistentClient(path=path_db)

def inicializar_sistema():
    """
    Crea la colección e inserta los 20 cursos solo si no existen previamente.
    """
    col_name = "cursos_epis"

    # Verificar si la colección ya existe para no duplicar datos
    colecciones = [c.name for c in client_persiste.list_collections()]

    if col_name in colecciones:
        print("💾 ESTADO: Base de datos persistente detectada. Cargando datos...")
        return client_persiste.get_collection(name=col_name, embedding_function=embedding_fn)

    print("🆕 ESTADO: Creando nueva base de datos y vectorizando 20 cursos...")
    coleccion = client_persiste.create_collection(name=col_name, embedding_function=embedding_fn)

    # Definición de los 20 cursos (Nombre, Semestre, Área, Prerrequisitos, Descripción)
    datos_cursos = [
        # Semestre 1 a 4
        {"n": "Introducción a la Programación", "s": 1, "a": "básica", "p": "Ninguno", "d": "Fundamentos de lógica y algoritmos computacionales. Uso de estructuras de control y tipos de datos simples. Introducción a la resolución de problemas."},
        {"n": "Cálculo I", "s": 1, "a": "básica", "p": "Ninguno", "d": "Estudio de límites, derivadas y continuidad de funciones reales. Aplicación de la matemática al análisis de cambios. Base para el modelado físico."},
        {"n": "Estructuras de Datos", "s": 3, "a": "especialidad", "p": "Programación II", "d": "Implementación de estructuras lineales y no lineales como árboles y grafos. Gestión eficiente de memoria y punteros. Algoritmos de búsqueda avanzada."},
        {"n": "Bases de Datos I", "s": 5, "a": "especialidad", "p": "Estructuras de Datos", "d": "Diseño de modelos entidad-relación y normalización de datos. Implementación en SQL y gestión de integridad referencial. Optimización de consultas complejas."},
        {"n": "Arquitectura de Computadores", "s": 4, "a": "especialidad", "p": "Sistemas Digitales", "d": "Organización interna de la CPU, memoria y periféricos. Programación en lenguaje ensamblador. Funcionamiento del hardware a bajo nivel."},

        # Semestre 5 a 8
        {"n": "Ingeniería de Software I", "s": 5, "a": "especialidad", "p": "Bases de Datos I", "d": "Ciclo de vida del software y captura de requerimientos. Introducción a patrones de diseño y modelado UML. Fundamentos de calidad de software."},
        {"n": "Inteligencia Artificial", "s": 7, "a": "especialidad", "p": "Estadística", "d": "Principios de aprendizaje automático y redes neuronales. Implementación de agentes inteligentes y algoritmos de búsqueda. Aplicación de lógica difusa."},
        {"n": "Redes de Computadoras", "s": 6, "a": "especialidad", "p": "Sistemas Operativos", "d": "Protocolos de comunicación y modelo OSI. Configuración de redes LAN y WAN mediante routers y switches. Administración de tráfico y servicios de red."},
        {"n": "Ciberseguridad", "s": 8, "a": "especialidad", "p": "Redes de Computadoras", "d": "Técnicas de defensa y ataque ético en entornos digitales. Implementación de criptografía y auditoría de sistemas. Protección de infraestructura crítica."},
        {"n": "Sistemas Operativos", "s": 5, "a": "especialidad", "p": "Arquitectura de Computadores", "d": "Gestión de procesos, hilos y planificación de CPU. Manejo de sistemas de archivos y memoria virtual. Interacción entre hardware y software."},

        # Electivos y Especialidad final
        {"n": "Computación en la Nube", "s": 9, "a": "electivo", "p": "Sistemas Distribuidos", "d": "Servicios de AWS, Azure y Google Cloud. Despliegue de microservicios y contenedores Docker. Escalabilidad y alta disponibilidad de aplicaciones."},
        {"n": "Desarrollo Móvil", "s": 7, "a": "electivo", "p": "Ingeniería de Software I", "d": "Creación de apps para Android e iOS usando frameworks modernos. Gestión de ciclo de vida de apps y sensores móviles. Conexión con APIs externas."},
        {"n": "Big Data", "s": 10, "a": "electivo", "p": "Bases de Datos II", "d": "Procesamiento de grandes volúmenes de datos con Hadoop y Spark. Análisis de datos no estructurados. Implementación de arquitecturas Lambda y Kappa."},
        {"n": "Interacción Hombre-Computador", "s": 8, "a": "especialidad", "p": "Software II", "d": "Diseño de interfaces de usuario centradas en la experiencia humana (UX). Pruebas de usabilidad y accesibilidad. Diseño visual y prototipado rápido."},
        {"n": "Internet de las Cosas (IoT)", "s": 9, "a": "electivo", "p": "Redes", "d": "Conexión de dispositivos físicos a la red mediante sensores y actuadores. Protocolos de comunicación ligera como MQTT. Desarrollo de ciudades inteligentes."},
        {"n": "Gestión de Proyectos TI", "s": 9, "a": "especialidad", "p": "Ingeniería de Software II", "d": "Marcos de trabajo ágiles como Scrum y Kanban. Gestión de tiempos, costos y riesgos en proyectos de software. Liderazgo de equipos técnicos."},
        {"n": "Simulación de Sistemas", "s": 6, "a": "especialidad", "p": "Cálculo II", "d": "Modelado matemático de eventos discretos. Uso de software especializado para predecir comportamientos de sistemas reales. Análisis de colas y procesos."},
        {"n": "Ética en la Ingeniería", "s": 2, "a": "básica", "p": "Ninguno", "d": "Análisis de la responsabilidad social del ingeniero. Dilemas éticos en el uso de la tecnología y manejo de datos. Normativa legal y deontología profesional."},
        {"n": "Física III", "s": 3, "a": "básica", "p": "Física II", "d": "Principios de electromagnetismo y circuitos eléctricos. Aplicación de las leyes de Maxwell. Fundamentos físicos para las comunicaciones."},
        {"n": "Sistemas Distribuidos", "s": 8, "a": "especialidad", "p": "Redes", "d": "Arquitecturas cliente-servidor y de múltiples capas. Sincronización de relojes y algoritmos de consenso. Tolerancia a fallos en redes complejas."}
    ]

    # Insertar los datos en ChromaDB
    coleccion.add(
        documents=[c['d'] for c in datos_cursos],
        metadatas=[{"nombre": c['n'], "semestre": c['s'], "area": c['a'], "prereq": c['p']} for c in datos_cursos],
        ids=[f"curso_{i+1:03d}" for i in range(len(datos_cursos))]
    )
    print("✅ Inserción completada exitosamente.")
    return coleccion

# Inicializar
coleccion_cursos = inicializar_sistema()

"""##FUNCIONES DE BÚSQUEDA Y MENÚ INTERACTIVO"""

# --- EJERCICIO 4: PASO 2 - FUNCIONES DE BÚSQUEDA Y MENÚ INTERACTIVO ---

def recomendar_cursos(intereses, semestre_max, top_k=3):
    """Recomienda cursos basados en intereses filtrando por semestre."""
    print(f"\nBuscando recomendaciones para: '{intereses}' (Hasta semestre {semestre_max})...")
    res = coleccion_cursos.query(
        query_texts=[intereses],
        n_results=top_k,
        where={"semestre": {"$lte": semestre_max}}
    )
    return res

def cursos_similares(nombre_curso, n=3):
    """Encuentra cursos parecidos a uno existente en la base de datos."""
    # 1. Recuperamos el curso base para obtener su descripción
    datos_base = coleccion_cursos.get(where={"nombre": nombre_curso})

    if not datos_base['documents']:
        print(f"❌ Error: El curso '{nombre_curso}' no existe. Verifica mayúsculas y tildes.")
        return None

    # 2. Buscamos similares usando la descripción del curso base
    print(f"\nBuscando cursos similares a '{nombre_curso}'...")
    res = coleccion_cursos.query(
        query_texts=[datos_base['documents'][0]],
        n_results=n + 1 # +1 porque se encontrará a sí mismo
    )
    return res

def buscar_por_perfil(habilidades, area_filtro='especialidad'):
    """Busca cursos según un perfil de habilidades y área específica."""
    perfil_texto = ", ".join(habilidades)
    print(f"\nBuscando cursos de {area_filtro} para el perfil: {perfil_texto}...")
    res = coleccion_cursos.query(
        query_texts=[perfil_texto],
        n_results=3,
        where={"area": {"$eq": area_filtro}}
    )
    return res

# --- INTERFAZ DE LÍNEA DE COMANDOS (MENÚ) ---

def mostrar_menu():
    while True:
        print("\n" + "="*45)
        print("🎓 SISTEMA DE RECOMENDACIÓN ACADÉMICA EPIS")
        print("="*45)
        print("1. Recomendar cursos por interés y semestre")
        print("2. Buscar cursos similares a uno (Relación)")
        print("3. Buscar cursos por perfil de habilidades")
        print("4. Salir")

        opcion = input("\nSeleccione una opción (1-4): ")

        if opcion == '1':
            interes = input("¿Qué te gustaría aprender? (ej: programación, redes, seguridad): ")
            sem = int(input("¿En qué semestre estás? (1-10): "))
            r = recomendar_cursos(interes, sem)
            print("\n✨ CURSOS RECOMENDADOS PARA TI:")
            for i in range(len(r['ids'][0])):
                meta = r['metadatas'][0][i]
                print(f" • {meta['nombre']} | Semestre: {meta['semestre']} | Área: {meta['area']}")

        elif opcion == '2':
            nombre = input("Ingresa el nombre del curso base (ej: Inteligencia Artificial): ")
            r = cursos_similares(nombre)
            if r:
                print(f"\n📚 CURSOS RELACIONADOS TEMÁTICAMENTE:")
                # Empezamos en 1 para no mostrar el mismo curso que ingresamos
                for i in range(1, len(r['ids'][0])):
                    meta = r['metadatas'][0][i]
                    print(f" • {meta['nombre']} | Semestre: {meta['semestre']}")

        elif opcion == '3':
            habs = input("Ingresa tus habilidades (separadas por comas): ").split(",")
            ar = input("Área de interés (básica / especialidad / electivo): ").lower()
            r = buscar_por_perfil(habs, ar)
            print("\n🎯 CURSOS QUE COINCIDEN CON TU PERFIL:")
            for i in range(len(r['ids'][0])):
                meta = r['metadatas'][0][i]
                print(f" • {meta['nombre']} | Requisito: {meta['prereq']}")

        elif opcion == '4':
            print("\n¡Gracias por usar el sistema EPIS! Cerrando sesión...")
            break
        else:
            print("Opcíon inválida. Intente de nuevo.")

# Lanzar el menú
mostrar_menu()